// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// debug_network_simplex
arma::mat debug_network_simplex(arma::mat cost, arma::vec a, arma::vec b);
RcppExport SEXP _manifoldalign_debug_network_simplex(SEXP costSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type cost(costSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(debug_network_simplex(cost, a, b));
    return rcpp_result_gen;
END_RCPP
}
// linear_sim_embed_cpp
Rcpp::List linear_sim_embed_cpp(const arma::mat& X, const arma::mat& T, const arma::mat& M, double sigma_P, int ncomp, double alpha_p, int maxit, double tol);
RcppExport SEXP _manifoldalign_linear_sim_embed_cpp(SEXP XSEXP, SEXP TSEXP, SEXP MSEXP, SEXP sigma_PSEXP, SEXP ncompSEXP, SEXP alpha_pSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_P(sigma_PSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_p(alpha_pSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(linear_sim_embed_cpp(X, T, M, sigma_P, ncomp, alpha_p, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// network_simplex_ot_cpp
Rcpp::NumericMatrix network_simplex_ot_cpp(Rcpp::NumericMatrix cost_r, Rcpp::NumericVector a_r, Rcpp::NumericVector b_r, double eps);
RcppExport SEXP _manifoldalign_network_simplex_ot_cpp(SEXP cost_rSEXP, SEXP a_rSEXP, SEXP b_rSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost_r(cost_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(network_simplex_ot_cpp(cost_r, a_r, b_r, eps));
    return rcpp_result_gen;
END_RCPP
}
// fallback_network_simplex_ot_cpp
Rcpp::NumericMatrix fallback_network_simplex_ot_cpp(Rcpp::NumericMatrix cost_r, Rcpp::NumericVector a_r, Rcpp::NumericVector b_r);
RcppExport SEXP _manifoldalign_fallback_network_simplex_ot_cpp(SEXP cost_rSEXP, SEXP a_rSEXP, SEXP b_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost_r(cost_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_r(b_rSEXP);
    rcpp_result_gen = Rcpp::wrap(fallback_network_simplex_ot_cpp(cost_r, a_r, b_r));
    return rcpp_result_gen;
END_RCPP
}
// partial_ot_mass_rcpp
Rcpp::NumericMatrix partial_ot_mass_rcpp(Rcpp::NumericMatrix cost_r, Rcpp::NumericVector a_r, Rcpp::NumericVector b_r, double mass, double eps);
RcppExport SEXP _manifoldalign_partial_ot_mass_rcpp(SEXP cost_rSEXP, SEXP a_rSEXP, SEXP b_rSEXP, SEXP massSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost_r(cost_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< double >::type mass(massSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(partial_ot_mass_rcpp(cost_r, a_r, b_r, mass, eps));
    return rcpp_result_gen;
END_RCPP
}
// compute_edge_distances_cpp
arma::mat compute_edge_distances_cpp(const arma::mat& X, const arma::sp_mat& A);
RcppExport SEXP _manifoldalign_compute_edge_distances_cpp(SEXP XSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(compute_edge_distances_cpp(X, A));
    return rcpp_result_gen;
END_RCPP
}
// compute_edge_gradient_cpp
arma::mat compute_edge_gradient_cpp(const arma::mat& S, const arma::sp_mat& A1, const arma::sp_mat& A2, const arma::mat& X1, const arma::mat& X2);
RcppExport SEXP _manifoldalign_compute_edge_gradient_cpp(SEXP SSEXP, SEXP A1SEXP, SEXP A2SEXP, SEXP X1SEXP, SEXP X2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_edge_gradient_cpp(S, A1, A2, X1, X2));
    return rcpp_result_gen;
END_RCPP
}
// compute_neighborhood_gradient_cpp
arma::mat compute_neighborhood_gradient_cpp(const arma::mat& S_prev, const arma::mat& W1, const arma::mat& W2, double eps);
RcppExport SEXP _manifoldalign_compute_neighborhood_gradient_cpp(SEXP S_prevSEXP, SEXP W1SEXP, SEXP W2SEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S_prev(S_prevSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_neighborhood_gradient_cpp(S_prev, W1, W2, eps));
    return rcpp_result_gen;
END_RCPP
}
// compute_anchor_gradient_cpp
arma::mat compute_anchor_gradient_cpp(const arma::mat& S_prev, const arma::uvec& anchor_idx1, const arma::uvec& anchor_idx2, const arma::vec& anchor_vals1, const arma::vec& anchor_vals2, double eps);
RcppExport SEXP _manifoldalign_compute_anchor_gradient_cpp(SEXP S_prevSEXP, SEXP anchor_idx1SEXP, SEXP anchor_idx2SEXP, SEXP anchor_vals1SEXP, SEXP anchor_vals2SEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S_prev(S_prevSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type anchor_idx1(anchor_idx1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type anchor_idx2(anchor_idx2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type anchor_vals1(anchor_vals1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type anchor_vals2(anchor_vals2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_anchor_gradient_cpp(S_prev, anchor_idx1, anchor_idx2, anchor_vals1, anchor_vals2, eps));
    return rcpp_result_gen;
END_RCPP
}
// normalize_doubly_stochastic_cpp
arma::mat normalize_doubly_stochastic_cpp(arma::mat S, const arma::vec& mu, const arma::vec& nu, double tol, int max_iter);
RcppExport SEXP _manifoldalign_normalize_doubly_stochastic_cpp(SEXP SSEXP, SEXP muSEXP, SEXP nuSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_doubly_stochastic_cpp(S, mu, nu, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// compute_squared_distances_cpp
arma::mat compute_squared_distances_cpp(const arma::mat& X1, const arma::mat& X2);
RcppExport SEXP _manifoldalign_compute_squared_distances_cpp(SEXP X1SEXP, SEXP X2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_squared_distances_cpp(X1, X2));
    return rcpp_result_gen;
END_RCPP
}
// solve_sylvester_rwr_cpp
arma::mat solve_sylvester_rwr_cpp(const arma::mat& W1, const arma::mat& W2T, const arma::mat& C_node, double beta, double gamma, double tol, int max_iter);
RcppExport SEXP _manifoldalign_solve_sylvester_rwr_cpp(SEXP W1SEXP, SEXP W2TSEXP, SEXP C_nodeSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W2T(W2TSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C_node(C_nodeSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_sylvester_rwr_cpp(W1, W2T, C_node, beta, gamma, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// compute_rwr_vectorized_cpp
arma::mat compute_rwr_vectorized_cpp(const arma::mat& W_transpose, const arma::mat& E, double sigma, int max_iter, double tol);
RcppExport SEXP _manifoldalign_compute_rwr_vectorized_cpp(SEXP W_transposeSEXP, SEXP ESEXP, SEXP sigmaSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type W_transpose(W_transposeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type E(ESEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_rwr_vectorized_cpp(W_transpose, E, sigma, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// compute_parrot_cost_cpp
arma::mat compute_parrot_cost_cpp(const arma::mat& X1, const arma::mat& X2, const arma::mat& R1, const arma::mat& R2, const arma::mat& W1, const arma::mat& W2, double alpha, double sigma, double gamma);
RcppExport SEXP _manifoldalign_compute_parrot_cost_cpp(SEXP X1SEXP, SEXP X2SEXP, SEXP R1SEXP, SEXP R2SEXP, SEXP W1SEXP, SEXP W2SEXP, SEXP alphaSEXP, SEXP sigmaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R1(R1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R2(R2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_parrot_cost_cpp(X1, X2, R1, R2, W1, W2, alpha, sigma, gamma));
    return rcpp_result_gen;
END_RCPP
}
// sinkhorn_unified
arma::mat sinkhorn_unified(const arma::mat& cost, const arma::vec& a, const arma::vec& b, double epsilon, int max_iter, double tol, bool stabilized);
RcppExport SEXP _manifoldalign_sinkhorn_unified(SEXP costSEXP, SEXP aSEXP, SEXP bSEXP, SEXP epsilonSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP stabilizedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cost(costSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type stabilized(stabilizedSEXP);
    rcpp_result_gen = Rcpp::wrap(sinkhorn_unified(cost, a, b, epsilon, max_iter, tol, stabilized));
    return rcpp_result_gen;
END_RCPP
}
// solve_sinkhorn_stabilized_cpp
arma::mat solve_sinkhorn_stabilized_cpp(const arma::mat& C_in, double tau, int max_iter, double tol);
RcppExport SEXP _manifoldalign_solve_sinkhorn_stabilized_cpp(SEXP C_inSEXP, SEXP tauSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C_in(C_inSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_sinkhorn_stabilized_cpp(C_in, tau, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// sinkhorn_ot_cpp
Rcpp::NumericMatrix sinkhorn_ot_cpp(Rcpp::NumericMatrix cost_r, Rcpp::NumericVector a_r, Rcpp::NumericVector b_r, double epsilon, int max_iter, double tol);
RcppExport SEXP _manifoldalign_sinkhorn_ot_cpp(SEXP cost_rSEXP, SEXP a_rSEXP, SEXP b_rSEXP, SEXP epsilonSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost_r(cost_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(sinkhorn_ot_cpp(cost_r, a_r, b_r, epsilon, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// has_lemon_network_simplex
bool has_lemon_network_simplex();
RcppExport SEXP _manifoldalign_has_lemon_network_simplex() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(has_lemon_network_simplex());
    return rcpp_result_gen;
END_RCPP
}
// test_network_simplex_minimal
arma::mat test_network_simplex_minimal();
RcppExport SEXP _manifoldalign_test_network_simplex_minimal() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_network_simplex_minimal());
    return rcpp_result_gen;
END_RCPP
}
// apply_tv_proximal_cpp
arma::mat apply_tv_proximal_cpp(const arma::mat& Y, double lambda);
RcppExport SEXP _manifoldalign_apply_tv_proximal_cpp(SEXP YSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_tv_proximal_cpp(Y, lambda));
    return rcpp_result_gen;
END_RCPP
}
// w2_cost_matrix_1d
Rcpp::List w2_cost_matrix_1d(Rcpp::NumericMatrix Uref, Rcpp::NumericMatrix Ug, Rcpp::NumericVector w_ref, Rcpp::NumericVector w_g);
RcppExport SEXP _manifoldalign_w2_cost_matrix_1d(SEXP UrefSEXP, SEXP UgSEXP, SEXP w_refSEXP, SEXP w_gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Uref(UrefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Ug(UgSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w_ref(w_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w_g(w_gSEXP);
    rcpp_result_gen = Rcpp::wrap(w2_cost_matrix_1d(Uref, Ug, w_ref, w_g));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP symbol(/* FIXME */);

static const R_CallMethodDef CallEntries[] = {
    {"_manifoldalign_debug_network_simplex", (DL_FUNC) &_manifoldalign_debug_network_simplex, 3},
    {"_manifoldalign_linear_sim_embed_cpp", (DL_FUNC) &_manifoldalign_linear_sim_embed_cpp, 8},
    {"_manifoldalign_network_simplex_ot_cpp", (DL_FUNC) &_manifoldalign_network_simplex_ot_cpp, 4},
    {"_manifoldalign_fallback_network_simplex_ot_cpp", (DL_FUNC) &_manifoldalign_fallback_network_simplex_ot_cpp, 3},
    {"_manifoldalign_partial_ot_mass_rcpp", (DL_FUNC) &_manifoldalign_partial_ot_mass_rcpp, 5},
    {"_manifoldalign_compute_edge_distances_cpp", (DL_FUNC) &_manifoldalign_compute_edge_distances_cpp, 2},
    {"_manifoldalign_compute_edge_gradient_cpp", (DL_FUNC) &_manifoldalign_compute_edge_gradient_cpp, 5},
    {"_manifoldalign_compute_neighborhood_gradient_cpp", (DL_FUNC) &_manifoldalign_compute_neighborhood_gradient_cpp, 4},
    {"_manifoldalign_compute_anchor_gradient_cpp", (DL_FUNC) &_manifoldalign_compute_anchor_gradient_cpp, 6},
    {"_manifoldalign_normalize_doubly_stochastic_cpp", (DL_FUNC) &_manifoldalign_normalize_doubly_stochastic_cpp, 5},
    {"_manifoldalign_compute_squared_distances_cpp", (DL_FUNC) &_manifoldalign_compute_squared_distances_cpp, 2},
    {"_manifoldalign_solve_sylvester_rwr_cpp", (DL_FUNC) &_manifoldalign_solve_sylvester_rwr_cpp, 7},
    {"_manifoldalign_compute_rwr_vectorized_cpp", (DL_FUNC) &_manifoldalign_compute_rwr_vectorized_cpp, 5},
    {"_manifoldalign_compute_parrot_cost_cpp", (DL_FUNC) &_manifoldalign_compute_parrot_cost_cpp, 9},
    {"_manifoldalign_sinkhorn_unified", (DL_FUNC) &_manifoldalign_sinkhorn_unified, 7},
    {"_manifoldalign_solve_sinkhorn_stabilized_cpp", (DL_FUNC) &_manifoldalign_solve_sinkhorn_stabilized_cpp, 4},
    {"_manifoldalign_sinkhorn_ot_cpp", (DL_FUNC) &_manifoldalign_sinkhorn_ot_cpp, 6},
    {"_manifoldalign_has_lemon_network_simplex", (DL_FUNC) &_manifoldalign_has_lemon_network_simplex, 0},
    {"_manifoldalign_test_network_simplex_minimal", (DL_FUNC) &_manifoldalign_test_network_simplex_minimal, 0},
    {"_manifoldalign_apply_tv_proximal_cpp", (DL_FUNC) &_manifoldalign_apply_tv_proximal_cpp, 2},
    {"_manifoldalign_w2_cost_matrix_1d", (DL_FUNC) &_manifoldalign_w2_cost_matrix_1d, 4},
    {"symbol", (DL_FUNC) &symbol, -1},
    {NULL, NULL, 0}
};

RcppExport void R_init_manifoldalign(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
