// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// linear_sim_embed_cpp
Rcpp::List linear_sim_embed_cpp(const arma::mat& X, const arma::mat& T, const arma::mat& M, double sigma_P, int ncomp, double alpha_p, int maxit, double tol);
RcppExport SEXP _manifoldalign_linear_sim_embed_cpp(SEXP XSEXP, SEXP TSEXP, SEXP MSEXP, SEXP sigma_PSEXP, SEXP ncompSEXP, SEXP alpha_pSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_P(sigma_PSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_p(alpha_pSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(linear_sim_embed_cpp(X, T, M, sigma_P, ncomp, alpha_p, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// network_simplex_ot_cpp
Rcpp::NumericMatrix network_simplex_ot_cpp(Rcpp::NumericMatrix cost_r, Rcpp::NumericVector a_r, Rcpp::NumericVector b_r, double eps);
RcppExport SEXP _manifoldalign_network_simplex_ot_cpp(SEXP cost_rSEXP, SEXP a_rSEXP, SEXP b_rSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost_r(cost_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(network_simplex_ot_cpp(cost_r, a_r, b_r, eps));
    return rcpp_result_gen;
END_RCPP
}
// fallback_network_simplex_ot_cpp
Rcpp::NumericMatrix fallback_network_simplex_ot_cpp(Rcpp::NumericMatrix cost_r, Rcpp::NumericVector a_r, Rcpp::NumericVector b_r);
RcppExport SEXP _manifoldalign_fallback_network_simplex_ot_cpp(SEXP cost_rSEXP, SEXP a_rSEXP, SEXP b_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost_r(cost_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_r(b_rSEXP);
    rcpp_result_gen = Rcpp::wrap(fallback_network_simplex_ot_cpp(cost_r, a_r, b_r));
    return rcpp_result_gen;
END_RCPP
}
// partial_ot_mass_rcpp
Rcpp::NumericMatrix partial_ot_mass_rcpp(Rcpp::NumericMatrix cost_r, Rcpp::NumericVector a_r, Rcpp::NumericVector b_r, double mass, double eps);
RcppExport SEXP _manifoldalign_partial_ot_mass_rcpp(SEXP cost_rSEXP, SEXP a_rSEXP, SEXP b_rSEXP, SEXP massSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost_r(cost_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< double >::type mass(massSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(partial_ot_mass_rcpp(cost_r, a_r, b_r, mass, eps));
    return rcpp_result_gen;
END_RCPP
}
// compute_edge_distances_cpp
arma::mat compute_edge_distances_cpp(const arma::mat& X, const arma::sp_mat& A);
RcppExport SEXP _manifoldalign_compute_edge_distances_cpp(SEXP XSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(compute_edge_distances_cpp(X, A));
    return rcpp_result_gen;
END_RCPP
}
// compute_edge_gradient_cpp
arma::mat compute_edge_gradient_cpp(const arma::mat& S, const arma::sp_mat& A1, const arma::sp_mat& A2, const arma::mat& X1, const arma::mat& X2);
RcppExport SEXP _manifoldalign_compute_edge_gradient_cpp(SEXP SSEXP, SEXP A1SEXP, SEXP A2SEXP, SEXP X1SEXP, SEXP X2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_edge_gradient_cpp(S, A1, A2, X1, X2));
    return rcpp_result_gen;
END_RCPP
}
// compute_neighborhood_gradient_cpp
arma::mat compute_neighborhood_gradient_cpp(const arma::mat& S_prev, const arma::mat& W1, const arma::mat& W2, double eps);
RcppExport SEXP _manifoldalign_compute_neighborhood_gradient_cpp(SEXP S_prevSEXP, SEXP W1SEXP, SEXP W2SEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S_prev(S_prevSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_neighborhood_gradient_cpp(S_prev, W1, W2, eps));
    return rcpp_result_gen;
END_RCPP
}
// compute_anchor_gradient_cpp
arma::mat compute_anchor_gradient_cpp(const arma::mat& S_prev, const arma::uvec& anchor_idx1, const arma::uvec& anchor_idx2, const arma::vec& anchor_vals1, const arma::vec& anchor_vals2, double eps);
RcppExport SEXP _manifoldalign_compute_anchor_gradient_cpp(SEXP S_prevSEXP, SEXP anchor_idx1SEXP, SEXP anchor_idx2SEXP, SEXP anchor_vals1SEXP, SEXP anchor_vals2SEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S_prev(S_prevSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type anchor_idx1(anchor_idx1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type anchor_idx2(anchor_idx2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type anchor_vals1(anchor_vals1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type anchor_vals2(anchor_vals2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_anchor_gradient_cpp(S_prev, anchor_idx1, anchor_idx2, anchor_vals1, anchor_vals2, eps));
    return rcpp_result_gen;
END_RCPP
}
// normalize_doubly_stochastic_cpp
arma::mat normalize_doubly_stochastic_cpp(arma::mat S, const arma::vec& mu, const arma::vec& nu, double tol, int max_iter);
RcppExport SEXP _manifoldalign_normalize_doubly_stochastic_cpp(SEXP SSEXP, SEXP muSEXP, SEXP nuSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_doubly_stochastic_cpp(S, mu, nu, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// compute_squared_distances_cpp
arma::mat compute_squared_distances_cpp(const arma::mat& X1, const arma::mat& X2);
RcppExport SEXP _manifoldalign_compute_squared_distances_cpp(SEXP X1SEXP, SEXP X2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_squared_distances_cpp(X1, X2));
    return rcpp_result_gen;
END_RCPP
}
// solve_sylvester_rwr_cpp
arma::mat solve_sylvester_rwr_cpp(const arma::mat& W1, const arma::mat& W2T, const arma::mat& C_node, double beta, double gamma, double tol, int max_iter);
RcppExport SEXP _manifoldalign_solve_sylvester_rwr_cpp(SEXP W1SEXP, SEXP W2TSEXP, SEXP C_nodeSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W2T(W2TSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C_node(C_nodeSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_sylvester_rwr_cpp(W1, W2T, C_node, beta, gamma, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// compute_rwr_vectorized_cpp
arma::mat compute_rwr_vectorized_cpp(const arma::mat& W_transpose, const arma::mat& E, double sigma, int max_iter, double tol);
RcppExport SEXP _manifoldalign_compute_rwr_vectorized_cpp(SEXP W_transposeSEXP, SEXP ESEXP, SEXP sigmaSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type W_transpose(W_transposeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type E(ESEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_rwr_vectorized_cpp(W_transpose, E, sigma, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// compute_parrot_cost_cpp
arma::mat compute_parrot_cost_cpp(const arma::mat& X1, const arma::mat& X2, const arma::mat& R1, const arma::mat& R2, const arma::mat& W1, const arma::mat& W2, double alpha, double sigma, double gamma);
RcppExport SEXP _manifoldalign_compute_parrot_cost_cpp(SEXP X1SEXP, SEXP X2SEXP, SEXP R1SEXP, SEXP R2SEXP, SEXP W1SEXP, SEXP W2SEXP, SEXP alphaSEXP, SEXP sigmaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R1(R1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R2(R2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_parrot_cost_cpp(X1, X2, R1, R2, W1, W2, alpha, sigma, gamma));
    return rcpp_result_gen;
END_RCPP
}
// sinkhorn_unified
arma::mat sinkhorn_unified(const arma::mat& cost, const arma::vec& a, const arma::vec& b, double epsilon, int max_iter, double tol, bool stabilized);
RcppExport SEXP _manifoldalign_sinkhorn_unified(SEXP costSEXP, SEXP aSEXP, SEXP bSEXP, SEXP epsilonSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP stabilizedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cost(costSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type stabilized(stabilizedSEXP);
    rcpp_result_gen = Rcpp::wrap(sinkhorn_unified(cost, a, b, epsilon, max_iter, tol, stabilized));
    return rcpp_result_gen;
END_RCPP
}
// sinkhorn_unified_potentials
Rcpp::List sinkhorn_unified_potentials(const arma::mat& cost, const arma::vec& a, const arma::vec& b, double epsilon, Rcpp::Nullable<Rcpp::NumericVector> log_u0, Rcpp::Nullable<Rcpp::NumericVector> log_v0, int max_iter, double tol, bool stabilized);
RcppExport SEXP _manifoldalign_sinkhorn_unified_potentials(SEXP costSEXP, SEXP aSEXP, SEXP bSEXP, SEXP epsilonSEXP, SEXP log_u0SEXP, SEXP log_v0SEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP stabilizedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cost(costSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type log_u0(log_u0SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type log_v0(log_v0SEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type stabilized(stabilizedSEXP);
    rcpp_result_gen = Rcpp::wrap(sinkhorn_unified_potentials(cost, a, b, epsilon, log_u0, log_v0, max_iter, tol, stabilized));
    return rcpp_result_gen;
END_RCPP
}
// solve_sinkhorn_stabilized_cpp
arma::mat solve_sinkhorn_stabilized_cpp(const arma::mat& C_in, double tau, int max_iter, double tol);
RcppExport SEXP _manifoldalign_solve_sinkhorn_stabilized_cpp(SEXP C_inSEXP, SEXP tauSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C_in(C_inSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_sinkhorn_stabilized_cpp(C_in, tau, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// sinkhorn_ot_cpp
Rcpp::NumericMatrix sinkhorn_ot_cpp(Rcpp::NumericMatrix cost_r, Rcpp::NumericVector a_r, Rcpp::NumericVector b_r, double epsilon, int max_iter, double tol);
RcppExport SEXP _manifoldalign_sinkhorn_ot_cpp(SEXP cost_rSEXP, SEXP a_rSEXP, SEXP b_rSEXP, SEXP epsilonSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cost_r(cost_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(sinkhorn_ot_cpp(cost_r, a_r, b_r, epsilon, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// has_lemon_network_simplex
bool has_lemon_network_simplex();
RcppExport SEXP _manifoldalign_has_lemon_network_simplex() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(has_lemon_network_simplex());
    return rcpp_result_gen;
END_RCPP
}
// apply_tv_proximal_cpp
arma::mat apply_tv_proximal_cpp(const arma::mat& Y, double lambda);
RcppExport SEXP _manifoldalign_apply_tv_proximal_cpp(SEXP YSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_tv_proximal_cpp(Y, lambda));
    return rcpp_result_gen;
END_RCPP
}
// uot_apply_map_dense_vec_cpp
arma::vec uot_apply_map_dense_vec_cpp(const arma::mat& cost, const arma::vec& alpha, const arma::vec& beta, const arma::vec& fbar, const arma::vec& gbar, double epsilon, const arma::vec& signal, double delta);
RcppExport SEXP _manifoldalign_uot_apply_map_dense_vec_cpp(SEXP costSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP fbarSEXP, SEXP gbarSEXP, SEXP epsilonSEXP, SEXP signalSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cost(costSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fbar(fbarSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gbar(gbarSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type signal(signalSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(uot_apply_map_dense_vec_cpp(cost, alpha, beta, fbar, gbar, epsilon, signal, delta));
    return rcpp_result_gen;
END_RCPP
}
// uot_apply_map_dense_mat_cpp
arma::mat uot_apply_map_dense_mat_cpp(const arma::mat& cost, const arma::vec& alpha, const arma::vec& beta, const arma::vec& fbar, const arma::vec& gbar, double epsilon, const arma::mat& signal, double delta);
RcppExport SEXP _manifoldalign_uot_apply_map_dense_mat_cpp(SEXP costSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP fbarSEXP, SEXP gbarSEXP, SEXP epsilonSEXP, SEXP signalSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cost(costSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fbar(fbarSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gbar(gbarSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type signal(signalSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(uot_apply_map_dense_mat_cpp(cost, alpha, beta, fbar, gbar, epsilon, signal, delta));
    return rcpp_result_gen;
END_RCPP
}
// uot_apply_map_sparse_vec_cpp
arma::vec uot_apply_map_sparse_vec_cpp(const Rcpp::IntegerVector& row_ptr, const Rcpp::IntegerVector& col_idx, const Rcpp::NumericVector& cost, int n_rows, int n_cols, const arma::vec& alpha, const arma::vec& beta, const arma::vec& fbar, const arma::vec& gbar, double epsilon, const arma::vec& signal, double delta);
RcppExport SEXP _manifoldalign_uot_apply_map_sparse_vec_cpp(SEXP row_ptrSEXP, SEXP col_idxSEXP, SEXP costSEXP, SEXP n_rowsSEXP, SEXP n_colsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP fbarSEXP, SEXP gbarSEXP, SEXP epsilonSEXP, SEXP signalSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type row_ptr(row_ptrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type col_idx(col_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type cost(costSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fbar(fbarSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gbar(gbarSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type signal(signalSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(uot_apply_map_sparse_vec_cpp(row_ptr, col_idx, cost, n_rows, n_cols, alpha, beta, fbar, gbar, epsilon, signal, delta));
    return rcpp_result_gen;
END_RCPP
}
// uot_apply_map_sparse_mat_cpp
arma::mat uot_apply_map_sparse_mat_cpp(const Rcpp::IntegerVector& col_ptr, const Rcpp::IntegerVector& row_idx, const Rcpp::NumericVector& cost_csc, int n_rows, int n_cols, const arma::vec& alpha, const arma::vec& beta, const arma::vec& fbar, const arma::vec& gbar, double epsilon, const arma::mat& signal, double delta);
RcppExport SEXP _manifoldalign_uot_apply_map_sparse_mat_cpp(SEXP col_ptrSEXP, SEXP row_idxSEXP, SEXP cost_cscSEXP, SEXP n_rowsSEXP, SEXP n_colsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP fbarSEXP, SEXP gbarSEXP, SEXP epsilonSEXP, SEXP signalSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type col_ptr(col_ptrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type row_idx(row_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type cost_csc(cost_cscSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fbar(fbarSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gbar(gbarSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type signal(signalSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(uot_apply_map_sparse_mat_cpp(col_ptr, row_idx, cost_csc, n_rows, n_cols, alpha, beta, fbar, gbar, epsilon, signal, delta));
    return rcpp_result_gen;
END_RCPP
}
// uot_extract_coupling_sparse_csc_cpp
Rcpp::List uot_extract_coupling_sparse_csc_cpp(const Rcpp::IntegerVector& col_ptr, const Rcpp::IntegerVector& row_idx, const Rcpp::NumericVector& cost_csc, int n_rows, int n_cols, const arma::vec& alpha, const arma::vec& beta, const arma::vec& fbar, const arma::vec& gbar, double epsilon, int weight_type, double delta, int topk_col, double threshold);
RcppExport SEXP _manifoldalign_uot_extract_coupling_sparse_csc_cpp(SEXP col_ptrSEXP, SEXP row_idxSEXP, SEXP cost_cscSEXP, SEXP n_rowsSEXP, SEXP n_colsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP fbarSEXP, SEXP gbarSEXP, SEXP epsilonSEXP, SEXP weight_typeSEXP, SEXP deltaSEXP, SEXP topk_colSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type col_ptr(col_ptrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type row_idx(row_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type cost_csc(cost_cscSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fbar(fbarSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gbar(gbarSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type weight_type(weight_typeSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type topk_col(topk_colSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(uot_extract_coupling_sparse_csc_cpp(col_ptr, row_idx, cost_csc, n_rows, n_cols, alpha, beta, fbar, gbar, epsilon, weight_type, delta, topk_col, threshold));
    return rcpp_result_gen;
END_RCPP
}
// uot_kl_logpi2_meanF_dense_cpp
Rcpp::List uot_kl_logpi2_meanF_dense_cpp(const arma::mat& cost, const arma::vec& alpha, const arma::vec& beta, const arma::vec& fbar, const arma::vec& gbar, double epsilon, Rcpp::Nullable<arma::mat> F);
RcppExport SEXP _manifoldalign_uot_kl_logpi2_meanF_dense_cpp(SEXP costSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP fbarSEXP, SEXP gbarSEXP, SEXP epsilonSEXP, SEXP FSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cost(costSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fbar(fbarSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gbar(gbarSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type F(FSEXP);
    rcpp_result_gen = Rcpp::wrap(uot_kl_logpi2_meanF_dense_cpp(cost, alpha, beta, fbar, gbar, epsilon, F));
    return rcpp_result_gen;
END_RCPP
}
// uot_kl_logpi2_meanF_sparse_cpp
Rcpp::List uot_kl_logpi2_meanF_sparse_cpp(const Rcpp::IntegerVector& row_ptr, const Rcpp::IntegerVector& col_idx, const Rcpp::NumericVector& cost, int n_rows, int n_cols, const arma::vec& alpha, const arma::vec& beta, const arma::vec& fbar, const arma::vec& gbar, double epsilon, Rcpp::Nullable<arma::mat> F);
RcppExport SEXP _manifoldalign_uot_kl_logpi2_meanF_sparse_cpp(SEXP row_ptrSEXP, SEXP col_idxSEXP, SEXP costSEXP, SEXP n_rowsSEXP, SEXP n_colsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP fbarSEXP, SEXP gbarSEXP, SEXP epsilonSEXP, SEXP FSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type row_ptr(row_ptrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type col_idx(col_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type cost(costSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fbar(fbarSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gbar(gbarSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type F(FSEXP);
    rcpp_result_gen = Rcpp::wrap(uot_kl_logpi2_meanF_sparse_cpp(row_ptr, col_idx, cost, n_rows, n_cols, alpha, beta, fbar, gbar, epsilon, F));
    return rcpp_result_gen;
END_RCPP
}
// uot_build_sparse_cost_knn_cpp
Rcpp::List uot_build_sparse_cost_knn_cpp(const Rcpp::IntegerMatrix& nn_idx, const Rcpp::NumericMatrix& nn_dists, int n_cols, double lambda_anat, Rcpp::Nullable<arma::mat> F, Rcpp::Nullable<arma::mat> G, double lambda_feat, double max_dist, Rcpp::Nullable<Rcpp::IntegerVector> extra_i, Rcpp::Nullable<Rcpp::IntegerVector> extra_j, Rcpp::Nullable<Rcpp::NumericVector> extra_dists, Rcpp::Nullable<arma::mat> Y_template, Rcpp::Nullable<Rcpp::IntegerVector> prior_map, double lambda_prior, double prior_sigma);
RcppExport SEXP _manifoldalign_uot_build_sparse_cost_knn_cpp(SEXP nn_idxSEXP, SEXP nn_distsSEXP, SEXP n_colsSEXP, SEXP lambda_anatSEXP, SEXP FSEXP, SEXP GSEXP, SEXP lambda_featSEXP, SEXP max_distSEXP, SEXP extra_iSEXP, SEXP extra_jSEXP, SEXP extra_distsSEXP, SEXP Y_templateSEXP, SEXP prior_mapSEXP, SEXP lambda_priorSEXP, SEXP prior_sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type nn_idx(nn_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type nn_dists(nn_distsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_anat(lambda_anatSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type F(FSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_feat(lambda_featSEXP);
    Rcpp::traits::input_parameter< double >::type max_dist(max_distSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type extra_i(extra_iSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type extra_j(extra_jSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type extra_dists(extra_distsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type Y_template(Y_templateSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type prior_map(prior_mapSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_prior(lambda_priorSEXP);
    Rcpp::traits::input_parameter< double >::type prior_sigma(prior_sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(uot_build_sparse_cost_knn_cpp(nn_idx, nn_dists, n_cols, lambda_anat, F, G, lambda_feat, max_dist, extra_i, extra_j, extra_dists, Y_template, prior_map, lambda_prior, prior_sigma));
    return rcpp_result_gen;
END_RCPP
}
// uot_ti_sinkhorn_kl_dense_cpp
Rcpp::List uot_ti_sinkhorn_kl_dense_cpp(const arma::mat& cost, const arma::vec& alpha, const arma::vec& beta, double epsilon, double rho1, double rho2, int max_iter, double tol);
RcppExport SEXP _manifoldalign_uot_ti_sinkhorn_kl_dense_cpp(SEXP costSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP epsilonSEXP, SEXP rho1SEXP, SEXP rho2SEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cost(costSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type rho1(rho1SEXP);
    Rcpp::traits::input_parameter< double >::type rho2(rho2SEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(uot_ti_sinkhorn_kl_dense_cpp(cost, alpha, beta, epsilon, rho1, rho2, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// uot_ti_sinkhorn_kl_sparse_cpp
Rcpp::List uot_ti_sinkhorn_kl_sparse_cpp(const Rcpp::IntegerVector& row_ptr, const Rcpp::IntegerVector& col_idx, const Rcpp::NumericVector& cost, int n_rows, int n_cols, const arma::vec& alpha, const arma::vec& beta, double epsilon, double rho1, double rho2, int max_iter, double tol);
RcppExport SEXP _manifoldalign_uot_ti_sinkhorn_kl_sparse_cpp(SEXP row_ptrSEXP, SEXP col_idxSEXP, SEXP costSEXP, SEXP n_rowsSEXP, SEXP n_colsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP epsilonSEXP, SEXP rho1SEXP, SEXP rho2SEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type row_ptr(row_ptrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type col_idx(col_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type cost(costSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type rho1(rho1SEXP);
    Rcpp::traits::input_parameter< double >::type rho2(rho2SEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(uot_ti_sinkhorn_kl_sparse_cpp(row_ptr, col_idx, cost, n_rows, n_cols, alpha, beta, epsilon, rho1, rho2, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// uot_ti_sinkhorn_kl_sparse_csr_csc_cpp
Rcpp::List uot_ti_sinkhorn_kl_sparse_csr_csc_cpp(const Rcpp::IntegerVector& row_ptr, const Rcpp::IntegerVector& col_idx, const Rcpp::NumericVector& cost, const Rcpp::IntegerVector& col_ptr, const Rcpp::IntegerVector& row_idx, const Rcpp::NumericVector& cost_csc, int n_rows, int n_cols, const arma::vec& alpha, const arma::vec& beta, double epsilon, double rho1, double rho2, int max_iter, double tol);
RcppExport SEXP _manifoldalign_uot_ti_sinkhorn_kl_sparse_csr_csc_cpp(SEXP row_ptrSEXP, SEXP col_idxSEXP, SEXP costSEXP, SEXP col_ptrSEXP, SEXP row_idxSEXP, SEXP cost_cscSEXP, SEXP n_rowsSEXP, SEXP n_colsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP epsilonSEXP, SEXP rho1SEXP, SEXP rho2SEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type row_ptr(row_ptrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type col_idx(col_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type cost(costSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type col_ptr(col_ptrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type row_idx(row_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type cost_csc(cost_cscSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type rho1(rho1SEXP);
    Rcpp::traits::input_parameter< double >::type rho2(rho2SEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(uot_ti_sinkhorn_kl_sparse_csr_csc_cpp(row_ptr, col_idx, cost, col_ptr, row_idx, cost_csc, n_rows, n_cols, alpha, beta, epsilon, rho1, rho2, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// w2_cost_matrix_1d
Rcpp::List w2_cost_matrix_1d(Rcpp::NumericMatrix Uref, Rcpp::NumericMatrix Ug, Rcpp::NumericVector w_ref, Rcpp::NumericVector w_g);
RcppExport SEXP _manifoldalign_w2_cost_matrix_1d(SEXP UrefSEXP, SEXP UgSEXP, SEXP w_refSEXP, SEXP w_gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Uref(UrefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Ug(UgSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w_ref(w_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w_g(w_gSEXP);
    rcpp_result_gen = Rcpp::wrap(w2_cost_matrix_1d(Uref, Ug, w_ref, w_g));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_manifoldalign_linear_sim_embed_cpp", (DL_FUNC) &_manifoldalign_linear_sim_embed_cpp, 8},
    {"_manifoldalign_network_simplex_ot_cpp", (DL_FUNC) &_manifoldalign_network_simplex_ot_cpp, 4},
    {"_manifoldalign_fallback_network_simplex_ot_cpp", (DL_FUNC) &_manifoldalign_fallback_network_simplex_ot_cpp, 3},
    {"_manifoldalign_partial_ot_mass_rcpp", (DL_FUNC) &_manifoldalign_partial_ot_mass_rcpp, 5},
    {"_manifoldalign_compute_edge_distances_cpp", (DL_FUNC) &_manifoldalign_compute_edge_distances_cpp, 2},
    {"_manifoldalign_compute_edge_gradient_cpp", (DL_FUNC) &_manifoldalign_compute_edge_gradient_cpp, 5},
    {"_manifoldalign_compute_neighborhood_gradient_cpp", (DL_FUNC) &_manifoldalign_compute_neighborhood_gradient_cpp, 4},
    {"_manifoldalign_compute_anchor_gradient_cpp", (DL_FUNC) &_manifoldalign_compute_anchor_gradient_cpp, 6},
    {"_manifoldalign_normalize_doubly_stochastic_cpp", (DL_FUNC) &_manifoldalign_normalize_doubly_stochastic_cpp, 5},
    {"_manifoldalign_compute_squared_distances_cpp", (DL_FUNC) &_manifoldalign_compute_squared_distances_cpp, 2},
    {"_manifoldalign_solve_sylvester_rwr_cpp", (DL_FUNC) &_manifoldalign_solve_sylvester_rwr_cpp, 7},
    {"_manifoldalign_compute_rwr_vectorized_cpp", (DL_FUNC) &_manifoldalign_compute_rwr_vectorized_cpp, 5},
    {"_manifoldalign_compute_parrot_cost_cpp", (DL_FUNC) &_manifoldalign_compute_parrot_cost_cpp, 9},
    {"_manifoldalign_sinkhorn_unified", (DL_FUNC) &_manifoldalign_sinkhorn_unified, 7},
    {"_manifoldalign_sinkhorn_unified_potentials", (DL_FUNC) &_manifoldalign_sinkhorn_unified_potentials, 9},
    {"_manifoldalign_solve_sinkhorn_stabilized_cpp", (DL_FUNC) &_manifoldalign_solve_sinkhorn_stabilized_cpp, 4},
    {"_manifoldalign_sinkhorn_ot_cpp", (DL_FUNC) &_manifoldalign_sinkhorn_ot_cpp, 6},
    {"_manifoldalign_has_lemon_network_simplex", (DL_FUNC) &_manifoldalign_has_lemon_network_simplex, 0},
    {"_manifoldalign_apply_tv_proximal_cpp", (DL_FUNC) &_manifoldalign_apply_tv_proximal_cpp, 2},
    {"_manifoldalign_uot_apply_map_dense_vec_cpp", (DL_FUNC) &_manifoldalign_uot_apply_map_dense_vec_cpp, 8},
    {"_manifoldalign_uot_apply_map_dense_mat_cpp", (DL_FUNC) &_manifoldalign_uot_apply_map_dense_mat_cpp, 8},
    {"_manifoldalign_uot_apply_map_sparse_vec_cpp", (DL_FUNC) &_manifoldalign_uot_apply_map_sparse_vec_cpp, 12},
    {"_manifoldalign_uot_apply_map_sparse_mat_cpp", (DL_FUNC) &_manifoldalign_uot_apply_map_sparse_mat_cpp, 12},
    {"_manifoldalign_uot_extract_coupling_sparse_csc_cpp", (DL_FUNC) &_manifoldalign_uot_extract_coupling_sparse_csc_cpp, 14},
    {"_manifoldalign_uot_kl_logpi2_meanF_dense_cpp", (DL_FUNC) &_manifoldalign_uot_kl_logpi2_meanF_dense_cpp, 7},
    {"_manifoldalign_uot_kl_logpi2_meanF_sparse_cpp", (DL_FUNC) &_manifoldalign_uot_kl_logpi2_meanF_sparse_cpp, 11},
    {"_manifoldalign_uot_build_sparse_cost_knn_cpp", (DL_FUNC) &_manifoldalign_uot_build_sparse_cost_knn_cpp, 15},
    {"_manifoldalign_uot_ti_sinkhorn_kl_dense_cpp", (DL_FUNC) &_manifoldalign_uot_ti_sinkhorn_kl_dense_cpp, 8},
    {"_manifoldalign_uot_ti_sinkhorn_kl_sparse_cpp", (DL_FUNC) &_manifoldalign_uot_ti_sinkhorn_kl_sparse_cpp, 12},
    {"_manifoldalign_uot_ti_sinkhorn_kl_sparse_csr_csc_cpp", (DL_FUNC) &_manifoldalign_uot_ti_sinkhorn_kl_sparse_csr_csc_cpp, 15},
    {"_manifoldalign_w2_cost_matrix_1d", (DL_FUNC) &_manifoldalign_w2_cost_matrix_1d, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_manifoldalign(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
