# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

debug_network_simplex <- function(cost, a, b) {
    .Call(`_manifoldalign_debug_network_simplex`, cost, a, b)
}

linear_sim_embed_cpp <- function(X, T, M, sigma_P, ncomp, alpha_p, maxit = 500L, tol = 1e-6) {
    .Call(`_manifoldalign_linear_sim_embed_cpp`, X, T, M, sigma_P, ncomp, alpha_p, maxit, tol)
}

network_simplex_ot_cpp <- function(cost_r, a_r, b_r, eps = 1e-9) {
    .Call(`_manifoldalign_network_simplex_ot_cpp`, cost_r, a_r, b_r, eps)
}

partial_ot_mass_rcpp <- function(cost_r, a_r, b_r, mass, eps = 1e-9) {
    .Call(`_manifoldalign_partial_ot_mass_rcpp`, cost_r, a_r, b_r, mass, eps)
}

#' Compute pairwise squared distances for connected nodes
#' 
#' @param X Feature matrix (n x d)
#' @param A Adjacency matrix (sparse, n x n)
#' @return Matrix of squared distances for edges
compute_edge_distances_cpp <- function(X, A) {
    .Call(`_manifoldalign_compute_edge_distances_cpp`, X, A)
}

#' Compute edge consistency gradient
#' 
#' Efficient computation of the gradient of edge consistency regularizer
#' 
#' @param S Current transport plan (n1 x n2)
#' @param A1 Adjacency matrix of network 1 (sparse)
#' @param A2 Adjacency matrix of network 2 (sparse)
#' @param X1 Features of network 1 (n1 x d)
#' @param X2 Features of network 2 (n2 x d)
#' @return Gradient matrix (n1 x n2)
compute_edge_gradient_cpp <- function(S, A1, A2, X1, X2) {
    .Call(`_manifoldalign_compute_edge_gradient_cpp`, S, A1, A2, X1, X2)
}

#' Compute neighborhood consistency gradient
#' 
#' Gradient of KL divergence term for neighborhood consistency
#' 
#' @param S_prev Previous transport plan
#' @param W1 Transition matrix of network 1
#' @param W2 Transition matrix of network 2
#' @param eps Small epsilon for numerical stability
#' @return Gradient matrix
compute_neighborhood_gradient_cpp <- function(S_prev, W1, W2, eps = 1e-16) {
    .Call(`_manifoldalign_compute_neighborhood_gradient_cpp`, S_prev, W1, W2, eps)
}

#' Compute anchor prior gradient
#' 
#' Gradient of KL divergence from anchor prior
#' 
#' @param S_prev Previous transport plan
#' @param anchor_idx1 Indices of anchors in network 1
#' @param anchor_idx2 Indices of anchors in network 2
#' @param anchor_vals1 Anchor values for network 1
#' @param anchor_vals2 Anchor values for network 2
#' @param eps Small epsilon for numerical stability
#' @return Gradient matrix
compute_anchor_gradient_cpp <- function(S_prev, anchor_idx1, anchor_idx2, anchor_vals1, anchor_vals2, eps = 1e-16) {
    .Call(`_manifoldalign_compute_anchor_gradient_cpp`, S_prev, anchor_idx1, anchor_idx2, anchor_vals1, anchor_vals2, eps)
}

normalize_doubly_stochastic_cpp <- function(S, mu, nu, tol = 1e-9, max_iter = 20L) {
    .Call(`_manifoldalign_normalize_doubly_stochastic_cpp`, S, mu, nu, tol, max_iter)
}

#' Compute squared Euclidean distance matrix
#' 
#' Efficient computation of pairwise squared distances
#' 
#' @param X1 First matrix (n1 x d)
#' @param X2 Second matrix (n2 x d)
#' @return Distance matrix (n1 x n2)
compute_squared_distances_cpp <- function(X1, X2) {
    .Call(`_manifoldalign_compute_squared_distances_cpp`, X1, X2)
}

#' Solve Sylvester equation for RWR cost
#' 
#' Iterative solution of: C_rwr = (1+β)C_node + (1-β)γ * W1 * C_rwr * W2^T
#' 
#' @param W1 Transition matrix of network 1
#' @param W2T Transpose of transition matrix of network 2
#' @param C_node Node-level cost matrix
#' @param beta RWR restart probability
#' @param gamma Cross-graph discount factor
#' @param tol Convergence tolerance
#' @param max_iter Maximum iterations
#' @return Solution matrix C_rwr
solve_sylvester_rwr_cpp <- function(W1, W2T, C_node, beta = 0.15, gamma = 0.1, tol = 1e-6, max_iter = 50L) {
    .Call(`_manifoldalign_solve_sylvester_rwr_cpp`, W1, W2T, C_node, beta, gamma, tol, max_iter)
}

#' Vectorized RWR computation
#' 
#' Compute Random Walk with Restart for multiple restart vectors simultaneously
#' 
#' @param W_transpose Transpose of transition matrix
#' @param E Matrix of restart vectors (columns are different restart distributions)
#' @param sigma Restart probability
#' @param max_iter Maximum iterations
#' @param tol Convergence tolerance
#' @return RWR result matrix
compute_rwr_vectorized_cpp <- function(W_transpose, E, sigma, max_iter, tol) {
    .Call(`_manifoldalign_compute_rwr_vectorized_cpp`, W_transpose, E, sigma, max_iter, tol)
}

#' Compute PARROT cost matrix
#' 
#' Complete cost matrix computation including Sylvester equation
#' 
#' @param X1 Features of network 1
#' @param X2 Features of network 2
#' @param R1 RWR descriptors of network 1
#' @param R2 RWR descriptors of network 2
#' @param W1 Transition matrix of network 1
#' @param W2 Transition matrix of network 2
#' @param alpha Weight for attribute vs RWR cost
#' @param sigma RWR restart probability
#' @param gamma Cross-graph discount factor
#' @return Position-aware cost matrix
compute_parrot_cost_cpp <- function(X1, X2, R1, R2, W1, W2, alpha = 0.5, sigma = 0.15, gamma = 0.1) {
    .Call(`_manifoldalign_compute_parrot_cost_cpp`, X1, X2, R1, R2, W1, W2, alpha, sigma, gamma)
}

#' Unified Sinkhorn algorithm with optional log-domain stabilization
#' 
#' @param cost Cost matrix (n x m)
#' @param a Source marginal (n x 1)
#' @param b Target marginal (m x 1)
#' @param epsilon Entropic regularization parameter
#' @param max_iter Maximum iterations
#' @param tol Convergence tolerance
#' @param stabilized Use log-domain stabilization for numerical stability
#' @return Transport plan matrix
sinkhorn_unified <- function(cost, a, b, epsilon, max_iter = 1000L, tol = 1e-9, stabilized = TRUE) {
    .Call(`_manifoldalign_sinkhorn_unified`, cost, a, b, epsilon, max_iter, tol, stabilized)
}

solve_sinkhorn_stabilized_cpp <- function(C_in, tau, max_iter, tol) {
    .Call(`_manifoldalign_solve_sinkhorn_stabilized_cpp`, C_in, tau, max_iter, tol)
}

sinkhorn_ot_cpp <- function(cost_r, a_r, b_r, epsilon, max_iter = 1000L, tol = 1e-9) {
    .Call(`_manifoldalign_sinkhorn_ot_cpp`, cost_r, a_r, b_r, epsilon, max_iter, tol)
}

has_lemon_network_simplex <- function() {
    .Call(`_manifoldalign_has_lemon_network_simplex`)
}

test_network_simplex_minimal <- function() {
    .Call(`_manifoldalign_test_network_simplex_minimal`)
}

apply_tv_proximal_cpp <- function(Y, lambda) {
    .Call(`_manifoldalign_apply_tv_proximal_cpp`, Y, lambda)
}

