# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linear_sim_embed_cpp <- function(X, T, M, sigma_P, ncomp, alpha_p, maxit = 500L, tol = 1e-6) {
    .Call(`_manifoldalign_linear_sim_embed_cpp`, X, T, M, sigma_P, ncomp, alpha_p, maxit, tol)
}

network_simplex_ot_cpp <- function(cost_r, a_r, b_r, eps = 1e-9) {
    .Call(`_manifoldalign_network_simplex_ot_cpp`, cost_r, a_r, b_r, eps)
}

fallback_network_simplex_ot_cpp <- function(cost_r, a_r, b_r) {
    .Call(`_manifoldalign_fallback_network_simplex_ot_cpp`, cost_r, a_r, b_r)
}

partial_ot_mass_rcpp <- function(cost_r, a_r, b_r, mass, eps = 1e-9) {
    .Call(`_manifoldalign_partial_ot_mass_rcpp`, cost_r, a_r, b_r, mass, eps)
}

#' Compute pairwise squared distances for connected nodes
#' 
#' @param X Feature matrix (n x d)
#' @param A Adjacency matrix (sparse, n x n)
#' @return Matrix of squared distances for edges
compute_edge_distances_cpp <- function(X, A) {
    .Call(`_manifoldalign_compute_edge_distances_cpp`, X, A)
}

#' Compute edge consistency gradient
#' 
#' Efficient computation of the gradient of edge consistency regularizer
#' 
#' @param S Current transport plan (n1 x n2)
#' @param A1 Adjacency matrix of network 1 (sparse)
#' @param A2 Adjacency matrix of network 2 (sparse)
#' @param X1 Features of network 1 (n1 x d)
#' @param X2 Features of network 2 (n2 x d)
#' @return Gradient matrix (n1 x n2)
compute_edge_gradient_cpp <- function(S, A1, A2, X1, X2) {
    .Call(`_manifoldalign_compute_edge_gradient_cpp`, S, A1, A2, X1, X2)
}

#' Compute neighborhood consistency gradient
#' 
#' Gradient of KL divergence term for neighborhood consistency
#' 
#' @param S_prev Previous transport plan
#' @param W1 Transition matrix of network 1
#' @param W2 Transition matrix of network 2
#' @param eps Small epsilon for numerical stability
#' @return Gradient matrix
compute_neighborhood_gradient_cpp <- function(S_prev, W1, W2, eps = 1e-16) {
    .Call(`_manifoldalign_compute_neighborhood_gradient_cpp`, S_prev, W1, W2, eps)
}

#' Compute anchor prior gradient
#' 
#' Gradient of KL divergence from anchor prior
#' 
#' @param S_prev Previous transport plan
#' @param anchor_idx1 Indices of anchors in network 1
#' @param anchor_idx2 Indices of anchors in network 2
#' @param anchor_vals1 Anchor values for network 1
#' @param anchor_vals2 Anchor values for network 2
#' @param eps Small epsilon for numerical stability
#' @return Gradient matrix
compute_anchor_gradient_cpp <- function(S_prev, anchor_idx1, anchor_idx2, anchor_vals1, anchor_vals2, eps = 1e-16) {
    .Call(`_manifoldalign_compute_anchor_gradient_cpp`, S_prev, anchor_idx1, anchor_idx2, anchor_vals1, anchor_vals2, eps)
}

normalize_doubly_stochastic_cpp <- function(S, mu, nu, tol = 1e-9, max_iter = 20L) {
    .Call(`_manifoldalign_normalize_doubly_stochastic_cpp`, S, mu, nu, tol, max_iter)
}

#' Compute squared Euclidean distance matrix
#' 
#' Efficient computation of pairwise squared distances
#' 
#' @param X1 First matrix (n1 x d)
#' @param X2 Second matrix (n2 x d)
#' @return Distance matrix (n1 x n2)
compute_squared_distances_cpp <- function(X1, X2) {
    .Call(`_manifoldalign_compute_squared_distances_cpp`, X1, X2)
}

#' Solve Sylvester equation for RWR cost
#' 
#' Iterative solution of: C_rwr = (1+β)C_node + (1-β)γ * W1 * C_rwr * W2^T
#' 
#' @param W1 Transition matrix of network 1
#' @param W2T Transpose of transition matrix of network 2
#' @param C_node Node-level cost matrix
#' @param beta RWR restart probability
#' @param gamma Cross-graph discount factor
#' @param tol Convergence tolerance
#' @param max_iter Maximum iterations
#' @return Solution matrix C_rwr
solve_sylvester_rwr_cpp <- function(W1, W2T, C_node, beta = 0.15, gamma = 0.1, tol = 1e-6, max_iter = 50L) {
    .Call(`_manifoldalign_solve_sylvester_rwr_cpp`, W1, W2T, C_node, beta, gamma, tol, max_iter)
}

#' Vectorized RWR computation
#' 
#' Compute Random Walk with Restart for multiple restart vectors simultaneously
#' 
#' @param W_transpose Transpose of transition matrix
#' @param E Matrix of restart vectors (columns are different restart distributions)
#' @param sigma Restart probability
#' @param max_iter Maximum iterations
#' @param tol Convergence tolerance
#' @return RWR result matrix
compute_rwr_vectorized_cpp <- function(W_transpose, E, sigma, max_iter, tol) {
    .Call(`_manifoldalign_compute_rwr_vectorized_cpp`, W_transpose, E, sigma, max_iter, tol)
}

#' Compute PARROT cost matrix
#' 
#' Complete cost matrix computation including Sylvester equation
#' 
#' @param X1 Features of network 1
#' @param X2 Features of network 2
#' @param R1 RWR descriptors of network 1
#' @param R2 RWR descriptors of network 2
#' @param W1 Transition matrix of network 1
#' @param W2 Transition matrix of network 2
#' @param alpha Weight for attribute vs RWR cost
#' @param sigma RWR restart probability
#' @param gamma Cross-graph discount factor
#' @return Position-aware cost matrix
compute_parrot_cost_cpp <- function(X1, X2, R1, R2, W1, W2, alpha = 0.5, sigma = 0.15, gamma = 0.1) {
    .Call(`_manifoldalign_compute_parrot_cost_cpp`, X1, X2, R1, R2, W1, W2, alpha, sigma, gamma)
}

#' Unified Sinkhorn algorithm with optional log-domain stabilization
#' 
#' @param cost Cost matrix (n x m)
#' @param a Source marginal (n x 1)
#' @param b Target marginal (m x 1)
#' @param epsilon Entropic regularization parameter
#' @param max_iter Maximum iterations
#' @param tol Convergence tolerance
#' @param stabilized Use log-domain stabilization for numerical stability
#' @return Transport plan matrix
sinkhorn_unified <- function(cost, a, b, epsilon, max_iter = 1000L, tol = 1e-9, stabilized = TRUE) {
    .Call(`_manifoldalign_sinkhorn_unified`, cost, a, b, epsilon, max_iter, tol, stabilized)
}

#' Unified Sinkhorn algorithm returning dual potentials for warm-starting
#'
#' This variant returns both the transport plan and the (log) scaling vectors
#' that can be reused to warm-start subsequent Sinkhorn solves.
#'
#' @param cost Cost matrix (n x m)
#' @param a Source marginal (n x 1)
#' @param b Target marginal (m x 1)
#' @param epsilon Entropic regularization parameter
#' @param log_u0 Optional warm-start log scaling for rows (length n)
#' @param log_v0 Optional warm-start log scaling for columns (length m)
#' @param max_iter Maximum iterations
#' @param tol Convergence tolerance
#' @param stabilized Use log-domain stabilization for small epsilon
#' @return A list with elements pi (plan), log_u, log_v
sinkhorn_unified_potentials <- function(cost, a, b, epsilon, log_u0 = NULL, log_v0 = NULL, max_iter = 1000L, tol = 1e-9, stabilized = TRUE) {
    .Call(`_manifoldalign_sinkhorn_unified_potentials`, cost, a, b, epsilon, log_u0, log_v0, max_iter, tol, stabilized)
}

solve_sinkhorn_stabilized_cpp <- function(C_in, tau, max_iter, tol) {
    .Call(`_manifoldalign_solve_sinkhorn_stabilized_cpp`, C_in, tau, max_iter, tol)
}

sinkhorn_ot_cpp <- function(cost_r, a_r, b_r, epsilon, max_iter = 1000L, tol = 1e-9) {
    .Call(`_manifoldalign_sinkhorn_ot_cpp`, cost_r, a_r, b_r, epsilon, max_iter, tol)
}

has_lemon_network_simplex <- function() {
    .Call(`_manifoldalign_has_lemon_network_simplex`)
}

apply_tv_proximal_cpp <- function(Y, lambda) {
    .Call(`_manifoldalign_apply_tv_proximal_cpp`, Y, lambda)
}

#' Apply UOT coupling as a barycentric map (dense, vector signal)
#'
#' Computes \eqn{\hat s_j = (\sum_i \pi_{ij} s_i) / (\pi_{2,j} + \delta)} without
#' materializing \eqn{\pi}, using translation-invariant potentials.
#'
#' @param cost Dense cost matrix (n x m).
#' @param alpha Source masses (length n).
#' @param beta Target masses (length m).
#' @param fbar Translation-invariant source potential (length n).
#' @param gbar Translation-invariant target potential (length m).
#' @param epsilon Entropic regularization parameter (> 0).
#' @param signal Source signal vector (length n).
#' @param delta Stabilizer added to the denominator.
#' @return A numeric vector (length m) in template space.
#' @export
uot_apply_map_dense_vec_cpp <- function(cost, alpha, beta, fbar, gbar, epsilon, signal, delta = 1e-8) {
    .Call(`_manifoldalign_uot_apply_map_dense_vec_cpp`, cost, alpha, beta, fbar, gbar, epsilon, signal, delta)
}

#' Apply UOT coupling as a barycentric map (dense, matrix signal)
#'
#' Matrix version for time series or multi-contrast signals.
#'
#' @param cost Dense cost matrix (n x m).
#' @param alpha Source masses (length n).
#' @param beta Target masses (length m).
#' @param fbar Translation-invariant source potential (length n).
#' @param gbar Translation-invariant target potential (length m).
#' @param epsilon Entropic regularization parameter (> 0).
#' @param signal Source signal matrix (T x n).
#' @param delta Stabilizer added to the denominator.
#' @return A numeric matrix (T x m) in template space.
#' @export
uot_apply_map_dense_mat_cpp <- function(cost, alpha, beta, fbar, gbar, epsilon, signal, delta = 1e-8) {
    .Call(`_manifoldalign_uot_apply_map_dense_mat_cpp`, cost, alpha, beta, fbar, gbar, epsilon, signal, delta)
}

#' Apply UOT coupling as a barycentric map (sparse, vector signal)
#'
#' Sparse version using a CSR-like row pointer representation.
#'
#' @param row_ptr Integer vector of length n+1 with CSR row offsets (0-based or
#'   1-based accepted; if 1-based, it must start at 0 or 1 and be nondecreasing).
#' @param col_idx Integer vector of length nnz giving 1-based column indices.
#' @param cost Numeric vector of length nnz aligned with `col_idx`.
#' @param n_rows Number of source nodes.
#' @param n_cols Number of target nodes.
#' @param alpha Source masses (length n_rows).
#' @param beta Target masses (length n_cols).
#' @param fbar Translation-invariant source potential (length n_rows).
#' @param gbar Translation-invariant target potential (length n_cols).
#' @param epsilon Entropic regularization parameter (> 0).
#' @param signal Source signal vector (length n_rows).
#' @param delta Stabilizer added to the denominator.
#' @return A numeric vector (length n_cols) in template space.
#' @export
uot_apply_map_sparse_vec_cpp <- function(row_ptr, col_idx, cost, n_rows, n_cols, alpha, beta, fbar, gbar, epsilon, signal, delta = 1e-8) {
    .Call(`_manifoldalign_uot_apply_map_sparse_vec_cpp`, row_ptr, col_idx, cost, n_rows, n_cols, alpha, beta, fbar, gbar, epsilon, signal, delta)
}

#' Apply UOT coupling as a barycentric map (sparse, matrix signal via CSC)
#'
#' Sparse matrix version for time series or multi-contrast signals. Requires a
#' CSC representation of the cost graph (column pointers + row indices).
#'
#' This computes \eqn{\hat S = S W / (\pi_2 + \delta)} without materializing
#' the full \eqn{\pi}. The implementation uses per-column log-stabilization to
#' avoid overflow in the exponential weights.
#'
#' @param col_ptr Integer vector of length m+1 with CSC column offsets (0-based
#'   or 1-based accepted; if 1-based, it must start at 0 or 1 and be nondecreasing).
#' @param row_idx Integer vector of length nnz giving 1-based row indices.
#' @param cost_csc Numeric vector of length nnz aligned with `row_idx`.
#' @param n_rows Number of source nodes.
#' @param n_cols Number of target nodes.
#' @param alpha Source masses (length n_rows).
#' @param beta Target masses (length n_cols).
#' @param fbar Translation-invariant source potential (length n_rows).
#' @param gbar Translation-invariant target potential (length n_cols).
#' @param epsilon Entropic regularization parameter (> 0).
#' @param signal Source signal matrix (T x n_rows).
#' @param delta Stabilizer added to the denominator.
#' @return A numeric matrix (T x n_cols) in template space.
#' @export
uot_apply_map_sparse_mat_cpp <- function(col_ptr, row_idx, cost_csc, n_rows, n_cols, alpha, beta, fbar, gbar, epsilon, signal, delta = 1e-8) {
    .Call(`_manifoldalign_uot_apply_map_sparse_mat_cpp`, col_ptr, row_idx, cost_csc, n_rows, n_cols, alpha, beta, fbar, gbar, epsilon, signal, delta)
}

#' Extract a sparse coupling / map operator from UOT dual potentials (CSC)
#'
#' Given translation-invariant dual potentials (fbar,gbar), compute edge weights
#' on a sparse cost graph in CSC form and return a `dgCMatrix`.
#'
#' Supported weight types:
#' - weight_type = 0: map operator weights, w_ij / (pi2_j + delta)
#' - weight_type = 1: conditional weights, w_ij / pi2_j (column-stochastic)
#' - weight_type = 2: raw coupling weights, w_ij
#'
#' Pruning is column-wise:
#' - keep only weights >= threshold (after weight_type transform)
#' - optionally keep only the topk_col largest weights per column
#'
#' @param col_ptr Integer vector of length m+1 with CSC column offsets (0-based
#'   or 1-based accepted; if 1-based, it must start at 0 or 1 and be nondecreasing).
#' @param row_idx Integer vector of length nnz giving 1-based row indices.
#' @param cost_csc Numeric vector of length nnz aligned with `row_idx`.
#' @param n_rows Number of source nodes.
#' @param n_cols Number of target nodes.
#' @param alpha Source masses (length n_rows).
#' @param beta Target masses (length n_cols).
#' @param fbar Translation-invariant source potential (length n_rows).
#' @param gbar Translation-invariant target potential (length n_cols).
#' @param epsilon Entropic regularization parameter (> 0).
#' @param weight_type See above (0,1,2).
#' @param delta Stabilizer for weight_type=0.
#' @param topk_col Optional top-k pruning per column (0 keeps all).
#' @param threshold Optional threshold pruning (<= 0 keeps all).
#' @return A list with `coupling` (dgCMatrix) and `log_pi2` (length n_cols).
#' @export
uot_extract_coupling_sparse_csc_cpp <- function(col_ptr, row_idx, cost_csc, n_rows, n_cols, alpha, beta, fbar, gbar, epsilon, weight_type = 0L, delta = 1e-8, topk_col = 0L, threshold = 0.0) {
    .Call(`_manifoldalign_uot_extract_coupling_sparse_csc_cpp`, col_ptr, row_idx, cost_csc, n_rows, n_cols, alpha, beta, fbar, gbar, epsilon, weight_type, delta, topk_col, threshold)
}

#' Compute log second marginal and transported feature means (dense)
#'
#' Given translation-invariant dual potentials (fbar,gbar), compute the log of
#' the second marginal (column sums) of the entropic UOT coupling and the
#' feature barycentric projection means per target node.
#'
#' @param cost Dense cost matrix (n x m).
#' @param alpha Source masses (length n).
#' @param beta Target masses (length m).
#' @param fbar Translation-invariant source potential (length n).
#' @param gbar Translation-invariant target potential (length m).
#' @param epsilon Entropic regularization parameter (> 0).
#' @param F Optional source features (n x D). If provided, returns mean features.
#' @return A list with `log_pi2` (length m) and optionally `mean_F` (m x D).
#' @export
uot_kl_logpi2_meanF_dense_cpp <- function(cost, alpha, beta, fbar, gbar, epsilon, F = NULL) {
    .Call(`_manifoldalign_uot_kl_logpi2_meanF_dense_cpp`, cost, alpha, beta, fbar, gbar, epsilon, F)
}

#' Compute log second marginal and transported feature means (sparse CSR)
#'
#' Same as `uot_kl_logpi2_meanF_dense_cpp` but for a sparse cost graph.
#'
#' @param row_ptr Integer vector of length n+1 with CSR row offsets (0-based or
#'   1-based accepted; if 1-based, it must start at 0 or 1 and be nondecreasing).
#' @param col_idx Integer vector of length nnz giving 1-based column indices.
#' @param cost Numeric vector of length nnz aligned with `col_idx`.
#' @param n_rows Number of source nodes.
#' @param n_cols Number of target nodes.
#' @param alpha Source masses (length n_rows).
#' @param beta Target masses (length n_cols).
#' @param fbar Translation-invariant source potential (length n_rows).
#' @param gbar Translation-invariant target potential (length n_cols).
#' @param epsilon Entropic regularization parameter (> 0).
#' @param F Optional source features (n_rows x D).
#' @return A list with `log_pi2` and optionally `mean_F`.
#' @export
uot_kl_logpi2_meanF_sparse_cpp <- function(row_ptr, col_idx, cost, n_rows, n_cols, alpha, beta, fbar, gbar, epsilon, F = NULL) {
    .Call(`_manifoldalign_uot_kl_logpi2_meanF_sparse_cpp`, row_ptr, col_idx, cost, n_rows, n_cols, alpha, beta, fbar, gbar, epsilon, F)
}

#' Build a sparse cost graph from neighbour indices/distances (CSR+CSC)
#'
#' Helper for CPU pipelines: given neighbor indices and distances (e.g. from
#' `RANN::nn2`), compute a sparse bipartite cost graph between source nodes and
#' a fixed template.
#'
#' @param nn_idx Integer matrix (n x k) of 1-based neighbor indices into the
#'   template support.
#' @param nn_dists Numeric matrix (n x k) of Euclidean distances aligned with
#'   `nn_idx`.
#' @param n_cols Number of template nodes (m).
#' @param lambda_anat Weight for anatomical distance-squared term.
#' @param F Optional source features (n x D).
#' @param G Optional template features (m x D).
#' @param lambda_feat Weight for feature distance-squared term.
#' @param max_dist Optional maximum distance threshold; edges with
#'   `nn_dists > max_dist` are dropped.
#' @param extra_i Optional 1-based row indices for additional edges.
#' @param extra_j Optional 1-based column indices for additional edges.
#' @param extra_dists Optional distances for additional edges (aligned to
#'   `extra_i`, `extra_j`).
#' @param Y_template Optional template coordinates/features (m x d). When
#'   provided together with `prior_map` and `lambda_prior > 0`, adds a soft
#'   diagonal/identity bias term based on squared distances in template space.
#' @param prior_map Optional integer vector (length n) giving the preferred
#'   template index (1..m) for each source node. Use NA for “no prior” on a row.
#' @param lambda_prior Nonnegative weight for the soft prior term.
#' @param prior_sigma Optional positive scale (in the units of `Y_template`).
#'   When finite, the prior penalty uses `||y_j - y_pref||^2 / prior_sigma^2`.
#' @return A list with CSR fields `row_ptr`, `col_idx`, `cost` and CSC fields
#'   `col_ptr`, `row_idx`, `cost_csc`, plus dimensions.
#' @export
uot_build_sparse_cost_knn_cpp <- function(nn_idx, nn_dists, n_cols, lambda_anat = 1.0, F = NULL, G = NULL, lambda_feat = 0.0, max_dist, extra_i = NULL, extra_j = NULL, extra_dists = NULL, Y_template = NULL, prior_map = NULL, lambda_prior = 0.0, prior_sigma = NA_real_) {
    .Call(`_manifoldalign_uot_build_sparse_cost_knn_cpp`, nn_idx, nn_dists, n_cols, lambda_anat, F, G, lambda_feat, max_dist, extra_i, extra_j, extra_dists, Y_template, prior_map, lambda_prior, prior_sigma)
}

#' KL translation-invariant Sinkhorn (dense cost)
#'
#' CPU implementation of the KL translation-invariant Sinkhorn updates for
#' entropic unbalanced OT with KL marginal penalties.
#'
#' @param cost Dense cost matrix (n x m).
#' @param alpha Source masses (length n, nonnegative, not all zero).
#' @param beta Target masses (length m, nonnegative, not all zero).
#' @param epsilon Entropic regularization parameter (> 0).
#' @param rho1 KL penalty on the first marginal (> 0).
#' @param rho2 KL penalty on the second marginal (> 0).
#' @param max_iter Maximum number of iterations.
#' @param tol Stopping tolerance on the infinity-norm iterate difference.
#' @return A list with translation-invariant potentials `fbar`, `gbar`,
#'   translated dual potentials `f`, `g`, translation `lambda`, iteration
#'   count, convergence flag, and last residual.
#' @export
uot_ti_sinkhorn_kl_dense_cpp <- function(cost, alpha, beta, epsilon, rho1, rho2, max_iter = 2000L, tol = 1e-6) {
    .Call(`_manifoldalign_uot_ti_sinkhorn_kl_dense_cpp`, cost, alpha, beta, epsilon, rho1, rho2, max_iter, tol)
}

#' KL translation-invariant Sinkhorn (sparse kNN cost)
#'
#' Sparse CPU implementation using a CSR-like row pointer representation.
#'
#' @param row_ptr Integer vector of length n+1 with CSR row offsets (0-based or
#'   1-based accepted; if 1-based, it must start at 0 or 1 and be nondecreasing).
#' @param col_idx Integer vector of length nnz giving 1-based column indices.
#' @param cost Numeric vector of length nnz giving cost values aligned with
#'   `col_idx`.
#' @param n_rows Number of source nodes (n).
#' @param n_cols Number of target nodes (m).
#' @param alpha Source masses (length n).
#' @param beta Target masses (length m).
#' @param epsilon Entropic regularization parameter (> 0).
#' @param rho1 KL penalty on the first marginal (> 0).
#' @param rho2 KL penalty on the second marginal (> 0).
#' @param max_iter Maximum number of iterations.
#' @param tol Stopping tolerance on the infinity-norm iterate difference.
#' @return A list with translation-invariant potentials `fbar`, `gbar`,
#'   translated dual potentials `f`, `g`, translation `lambda`, iteration
#'   count, convergence flag, and last residual.
#' @export
uot_ti_sinkhorn_kl_sparse_cpp <- function(row_ptr, col_idx, cost, n_rows, n_cols, alpha, beta, epsilon, rho1, rho2, max_iter = 2000L, tol = 1e-6) {
    .Call(`_manifoldalign_uot_ti_sinkhorn_kl_sparse_cpp`, row_ptr, col_idx, cost, n_rows, n_cols, alpha, beta, epsilon, rho1, rho2, max_iter, tol)
}

#' KL translation-invariant Sinkhorn (sparse CSR+CSC cost)
#'
#' Sparse CPU implementation using both CSR and CSC representations.
#' This improves cache locality and enables per-column parallelism.
#'
#' @param row_ptr Integer vector of length n+1 with CSR row offsets (0-based or
#'   1-based accepted; if 1-based, it must start at 0 or 1 and be nondecreasing).
#' @param col_idx Integer vector of length nnz giving 1-based column indices.
#' @param cost Numeric vector of length nnz giving cost values aligned with
#'   `col_idx`.
#' @param col_ptr Integer vector of length m+1 with CSC column offsets (0-based
#'   or 1-based accepted).
#' @param row_idx Integer vector of length nnz giving 1-based row indices.
#' @param cost_csc Numeric vector of length nnz aligned with `row_idx`.
#' @param n_rows Number of source nodes (n).
#' @param n_cols Number of target nodes (m).
#' @param alpha Source masses (length n).
#' @param beta Target masses (length m).
#' @param epsilon Entropic regularization parameter (> 0).
#' @param rho1 KL penalty on the first marginal (> 0).
#' @param rho2 KL penalty on the second marginal (> 0).
#' @param max_iter Maximum number of iterations.
#' @param tol Stopping tolerance on the infinity-norm iterate difference.
#' @return A list with translation-invariant potentials `fbar`, `gbar`,
#'   translated dual potentials `f`, `g`, translation `lambda`, iteration
#'   count, convergence flag, last residual, and backend tag.
#' @export
uot_ti_sinkhorn_kl_sparse_csr_csc_cpp <- function(row_ptr, col_idx, cost, col_ptr, row_idx, cost_csc, n_rows, n_cols, alpha, beta, epsilon, rho1, rho2, max_iter = 2000L, tol = 1e-6) {
    .Call(`_manifoldalign_uot_ti_sinkhorn_kl_sparse_csr_csc_cpp`, row_ptr, col_idx, cost, col_ptr, row_idx, cost_csc, n_rows, n_cols, alpha, beta, epsilon, rho1, rho2, max_iter, tol)
}

w2_cost_matrix_1d <- function(Uref, Ug, w_ref, w_g) {
    .Call(`_manifoldalign_w2_cost_matrix_1d`, Uref, Ug, w_ref, w_g)
}

